name: CD
on: [workflow_dispatch]
jobs:
  # This workflow contains a single job called  "hello"
  hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: helloweurldz
      run : echo 'Hello simplonz'